name: "Build & Release"

on:
  pull_request:
    branches:
      - dev

  push:
    branches:
      - dev
env:
  test: ${{ secrets.TOKEN }}
  
jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
    # Show how to print unmasked GitHub secrets to the console
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
         echo ${{env.test}}
         echo "Trick to echo GitHub Actions Secret:  "
         echo ${{env.test}} | sed 's/./& /g'
      
      #1 Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      #2 Setup Java
      - name: Set-up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'oracle'
          java-version: '17'

      #3 Setup Flutter
      - name: Set-up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'
          channel: 'stable'

      #4 Install Dependencies
      - name: Install Dependencies
        run: flutter pub get

      #6 Run Test
      - name: Test Flutter App
        run: flutter test

      #7 Build APK
      - name: Build APK
        run: flutter build apk --release

      #8 Build AAB
      - name: Build appBundle
        run: flutter build appbundle

      #9 Get those Build to be available to download
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Releases
          path: build/app/outputs/flutter-apk/app-release.apk
            # build/app/outputs/bundle/release/app-release.aab
#            build/ios_build.tar.gz

      #10 Create Release with Those Builds
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          tag: v1.0.${{ github.run_number }}
          token: ${{ env.test }}
